version: '3'
services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - '6500:6500'
    env_file:
      - ./.env
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
